---
project-file: stm32f0-usbd-devboard.kicad_pro
pcb-render:
  include-dnp: true
  width: 1840
  height: 4320
  zoom: 0.75
  pan:
    y: 0.8
  scales:
    - 480
    - 720
    - 1080
  sides:
    - top
    - bottom
pcb-ibom:
  enable: true
pcb-gerber:
  copy-pattern: gerber/*.zip
sch-export-pdf:
  enable: true
